import type { SecretFinding, SecretPolicy } from "../types.js";
import { shortHash, sha256 } from "./hash.js";

interface Rule {
  name: string;
  re: RegExp;
}

// Tuned to the real secrets found in this user's memory, plus common token shapes.
const DEFAULT_RULES: Rule[] = [
  { name: "slack-webhook", re: /https:\/\/hooks\.slack\.com\/services\/\S+/g },
  { name: "clickup-pk", re: /\bpk_\d+_[A-Z0-9]{20,}\b/g },
  { name: "openai-sk", re: /\bsk-[A-Za-z0-9_-]{20,}\b/g },
  { name: "github-pat", re: /\bghp_[A-Za-z0-9]{20,}\b/g },
  { name: "aws-akia", re: /\bAKIA[0-9A-Z]{16}\b/g },
  { name: "hf-token", re: /\bhf_[A-Za-z0-9]{20,}\b/g },
  // Keyword can sit anywhere in the identifier (e.g. SLACK_WEBHOOK_URL, MY_API_KEY_V2).
  { name: "env-assignment", re: /\b[A-Z][A-Z0-9_]*(TOKEN|SECRET|API[_-]?KEY|WEBHOOK|PASSWORD)[A-Z0-9_]*\b\s*[=:]\s*\S+/g },
];

function buildRules(policy: SecretPolicy): Rule[] {
  const extra = policy.customPatterns.map((p, i) => ({ name: `custom-${i}`, re: new RegExp(p, "g") }));
  return [...DEFAULT_RULES, ...extra];
}

function previewOf(match: string): string {
  if (match.length <= 12) return match.slice(0, 3) + "…";
  return `${match.slice(0, 6)}…${match.slice(-4)}`;
}

/** Scan a single string; line numbers are 1-based within `content`. */
export function scanContent(content: string, file: string, policy: SecretPolicy): SecretFinding[] {
  const rules = buildRules(policy);
  const ignore = policy.ignorePatterns.map((p) => new RegExp(p));
  const findings: SecretFinding[] = [];
  const seen = new Set<string>();
  for (const rule of rules) {
    rule.re.lastIndex = 0;
    let m: RegExpExecArray | null;
    while ((m = rule.re.exec(content)) !== null) {
      const match = m[0];
      if (ignore.some((ig) => ig.test(match))) continue;
      const key = `${rule.name}:${match}`;
      if (seen.has(key)) continue;
      seen.add(key);
      const line = content.slice(0, m.index).split("\n").length;
      findings.push({ file, line, rule: rule.name, preview: previewOf(match), match });
    }
  }
  return findings;
}

// ---- redact / expand transforms (applied around render/parse) ----

const PLACEHOLDER_RE = /«ccsync-secret:([0-9a-f]{12})»/g;

export interface RedactionResult {
  redacted: string;
  /** placeholderId -> real secret string. */
  mapping: Record<string, string>;
}

/** Replace every detected secret in `text` with a stable placeholder token. */
export function applyRedaction(text: string, policy: SecretPolicy): RedactionResult {
  const findings = scanContent(text, "<agents>", policy);
  const mapping: Record<string, string> = {};
  let redacted = text;
  // Replace longest matches first to avoid partial-overlap issues.
  const uniques = [...new Set(findings.map((f) => f.match))].sort((a, b) => b.length - a.length);
  for (const secret of uniques) {
    const id = shortHash(sha256(secret));
    mapping[id] = secret;
    redacted = redacted.split(secret).join(`«ccsync-secret:${id}»`);
  }
  return { redacted, mapping };
}

/** Re-expand placeholders using a mapping (inverse of applyRedaction). */
export function expandRedaction(text: string, mapping: Record<string, string>): string {
  return text.replace(PLACEHOLDER_RE, (whole, id: string) => mapping[id] ?? whole);
}

export function serializeSidecar(mapping: Record<string, string>): string {
  const lines = [
    "<!-- ccsync secret sidecar — gitignored. Real values for AGENTS.md placeholders. -->",
    "<!-- Do NOT commit. Generated by cc-codex-sync. -->",
    "",
  ];
  for (const [id, secret] of Object.entries(mapping)) {
    lines.push(`${id}\t${secret}`);
  }
  return lines.join("\n") + "\n";
}

export function parseSidecar(content: string | null): Record<string, string> {
  const mapping: Record<string, string> = {};
  if (!content) return mapping;
  for (const raw of content.split(/\r?\n/)) {
    if (!raw || raw.startsWith("<!--")) continue;
    const tab = raw.indexOf("\t");
    if (tab === -1) continue;
    mapping[raw.slice(0, tab)] = raw.slice(tab + 1);
  }
  return mapping;
}
